name: IntensifyReforged
version: '1.0.0 - alpha'
main: net.quepierts.intensify.IntensifyReforgedPlugin
api-version: 1.16
authors: [ Louis_Quepierts ]
description: non
commands:
  intensify:
    permission: intensify.admin

permissions:
  intensify.admin:
    default: op